name: Android Build

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Run Java Linter
        run: bash ./gradlew lint --stacktrace

      # Step 3: Check the code with Android linter
      - name: Run Android KTLint
        run: bash ./gradlew ktlintCheck --stacktrace

      # Step 3: Check the code with Android format
      - name: Run Android KTFormat
        run: bash ./gradlew ktlintFormat --stacktrace

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
